### ISSUE TITLE
'admob_flutter/admob_flutter-Swift.h' file not found

### ISSUE THREAD

**Issue by Long2k1708** [YoussefKababe/admob_flutter#22]
I'm using XCode 10.2.1 to build. After install this library, i've got this error in AdmobFlutterPlugin.m
```
#import "AdmobFlutterPlugin.h"
#import <admob_flutter/admob_flutter-Swift.h> // Error in this line: 'admob_flutter/admob_flutter-Swift.h' file not found

@implementation AdmobFlutterPlugin
+ (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar>*)registrar {
  [SwiftAdmobFlutterPlugin registerWithRegistrar:registrar];
}
@end
```
How to fix this error? :(
And, how to skip install this library when i execute `pod install`? Because i want this library only work with android.

**Comment by jendy2012** [comment]
https://github.com/ko2ic/image_downloader/wiki#your-appdelegate-is-the-case-of-objective-c

**Comment by mmahkamov** [comment]
This happens when your Flutter app was created without Swift support on the iOS side.

Read this comment to add Swift support to your Flutter app: https://github.com/flutter/flutter/issues/16049#issuecomment-382629492

For Xcode 10.2 you'll need to specify 4.0, 4.2 or 5.0 as SWIFT_VERSION.

Worked for me.

**Comment by Long2k1708** [comment]
Thank you so much! I fixed this problem! <3
