### ISSUE TITLE
Feature Request: Targeting Support (Similar to Official Plugin)

### ISSUE THREAD

**Issue by gcshri** [YoussefKababe/admob_flutter#7]
@YoussefKababe - Just adding a request to get to, whenever you can in the future.

Can we get targeting support? Lack of keywords and contenturl seems to make a radical difference in the quality of ads that we see using this plugin.

From the original plugin docs:

```
MobileAdTargetingInfo targetingInfo = MobileAdTargetingInfo(
  keywords: <String>['flutterio', 'beautiful apps'],
  contentUrl: 'https://flutter.io',
  birthday: DateTime.now(),
  childDirected: false,
  designedForFamilies: false,
  gender: MobileAdGender.male, // or MobileAdGender.female, MobileAdGender.unknown
  testDevices: <String>[], // Android emulators are considered test devices
);
```

**Comment by kmcgill88** [comment]
@Purus can you please link documentation of the Admob library deprecating target info?

Thanks!

**Comment by gcshri** [comment]
@kmcgill88 Look for the 2018-05-10 update in the release notes: 

https://developers.google.com/admob/android/rel-notes

**Comment by kmcgill88** [comment]
@Purus that link says 
```
Deprecated the following methods on AdRequest.Builder.
setGender()
setBirthday()
setIsDesignedForFamiles()
```

Is this all targeting info?

**Comment by Purus** [comment]
Yes. If you have noticed, the office flutter plugin for Admob has also
marked these parameters for targetting as depreciated.

Thanks,

Purusothaman Ramanujam

**Comment by kmcgill88** [comment]
@Purus, interesting I didn't know that! Sounds like we can close this issue.

**Comment by gcshri** [comment]
These two do add relevancy.

Anyways, your call. We've moved to the Ad Manager plugin.

**Comment by kmcgill88** [comment]
@gcshri [flutter_google_ad_manager](https://github.com/ko2ic/flutter_google_ad_manager) looks very nice too! If anyone else finds this issue, this [Stackoverflow post](https://stackoverflow.com/questions/23340455/difference-between-admob-and-dfp-networks) has a good explanation of the difference between DoubleClick for Publishers (DFP) and Admob. Seems like a slightly different use case to me. We could probably learn some implementation details from both projects because of the similarities.

**Comment by zmeggyesi** [comment]
What about `keywords` and `contentUrl`? Those don't seem to be deprecated, but I cannot set them in the plugin. Or at least I'm missing how.

Can I get some pointers on how to change the keywords for targeting? I'm looking to do a fairly specific set of keywords and ads to keep with my app's theme.

**Comment by DhiaEddineNabli** [comment]
@zmeggyesi thank you for implementing the targeting info to Banner ads. Indeed this very relevant since there got be a way to control the ads content and google is very strict about it. Is the targeting info feature now available at least for android in the new version of the admob_flutter package when downloading it from https://pub.dev/packages ?

**Comment by zmeggyesi** [comment]
Hi,

I don't think so, the PR is not merged yet. You can set up Pub to track a
Git repository and branch, though, so you can take advantage of it.

Best regards,
Zalán Meggyesi
